name: Release Helm ETH Node

on: [workflow_dispatch]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: helm
      
      - name: Checkout eth node repo
        uses: actions/checkout@v2
        with:
          repository: avolens/helm-eth-node
          path: eth-node

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Package and index
        run: |
          helm package --destination releases-new eth-node
          helm repo index releases-new --merge helm/releases/index.yaml --url https://helm.avolens.com/releases
          mv releases-new/* helm/releases
          
      - name: Update repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated ETH Node Helm chart release"
          cwd: helm
          default_author: github_actions
